### ISSUE TITLE
 profile "curryhot" not working

### ISSUE THREAD

**Issue by aryankori** [Ananto30/steam-stat#15]
The Steam stats card generator works for other profiles but does not display stats for my profile named "curryhot."  I confirmed that my profile is public and that the name is correct. Other profiles load without issue.

Steps to reproduce:

-  Open: [My Steam Stats](https://steam-stat.vercel.app/api?profileName=curryhot)
-  No stats are displayed.
-  Replace "curryhot" with another profile name to see if it works correctly.

![image](https://github.com/Ananto30/steam-stat/assets/48612780/2330d92c-de7b-4321-9078-a4ec4e141916)

**Comment by Ananto30** [comment]
Fixed here https://github.com/Ananto30/steam-stat/pull/16


<img width="500" alt="Screenshot 2024-06-19 at 21 09 24" src="https://github.com/Ananto30/steam-stat/assets/15931537/68f8a8f2-c05b-4437-9f0c-a82d6cfddd26">
