### ISSUE TITLE
Render error 

### ISSUE THREAD

**Issue by KeoFoxy** [Ananto30/steam-stat#9]
Hi

I have an issue: when Im trying to render my stats in README.md Github I get an error

> This page contains the following errors: 
error on line 71 at column 36: AttValue: ' expected
Below is a rendering of the page up to the first error.   

And it stops rendering stats.
if I use a link with my ID in browser everything is good https://steam-stat.vercel.app/api?profileName=KeoFoxy
But
`<img src="https://steam-stat.vercel.app/api?profileName=KeoFoxy"/>`
<img src="https://steam-stat.vercel.app/api?profileName=KeoFoxy"/>

**Comment by KeoFoxy** [comment]
![image](https://user-images.githubusercontent.com/45719053/213887736-3b6e0a61-5479-4edd-bf0b-fac6cc156b63.png)

**Comment by KeoFoxy** [comment]
From now it renders correctly but gives a bad link and img does not show up

**Comment by Ananto30** [comment]
I guess it worked? :3

**Comment by KeoFoxy** [comment]
Yeah :)
